version: '3'
services:
    medialinker:
        restart: always
        volumes:
            - '/volume1/docker/medialinker/constant.js:/opt/constant.js'
        environment:
            - AUTO_UPDATE=false
            - SERVER=emby
            - NGINX_PORT=8091
            - NGINX_SSL_PORT=8095

        container_name: medialinker
        image: 'thsrite/medialinker:latest'
        network_mode: "host"